/*
 * OpenAI（ChatGPT）
 *
 * Open AI（ChatGPT）几乎可以应用于任何涉及理解或生成自然语言或代码的任务。我们提供一系列具有不同功率级别的模型，适用于不同的任务，并且能够微调您自己的自定义模型。这些模型可用于从内容生成到语义搜索和分类的所有领域。  
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"github.com/gin-gonic/gin"
)

type AssistantsBetaAPI struct {
}

// Delete /v1/assistants/:assistant_id 
// 删除助手 
func (api *AssistantsBetaAPI) V1AssistantsAssistantIdDelete(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Delete /v1/assistants/:assistant_id/files/:file_id 
// 删除辅助文件 
func (api *AssistantsBetaAPI) V1AssistantsAssistantIdFilesFileIdDelete(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Get /v1/assistants/:assistant_id/files/:file_id 
// 检索助手文件 
func (api *AssistantsBetaAPI) V1AssistantsAssistantIdFilesFileIdGet(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Get /v1/assistants/:assistant_id/files
// 列出助手文件 
func (api *AssistantsBetaAPI) V1AssistantsAssistantIdFilesGet(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Post /v1/assistants/:assistant_id/files
// 创建辅助文件 
func (api *AssistantsBetaAPI) V1AssistantsAssistantIdFilesPost(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Get /v1/assistants/:assistant_id
// 检索助手 
func (api *AssistantsBetaAPI) V1AssistantsAssistantIdGet(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Post /v1/assistants/:assistant_id 
// 修改助手 
func (api *AssistantsBetaAPI) V1AssistantsAssistantIdPost(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Get /v1/assistants
// 列出助手 
func (api *AssistantsBetaAPI) V1AssistantsGet(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Post /v1/assistants
// 创建助手 
func (api *AssistantsBetaAPI) V1AssistantsPost(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

