/*
 * OpenAI（ChatGPT）
 *
 * Open AI（ChatGPT）几乎可以应用于任何涉及理解或生成自然语言或代码的任务。我们提供一系列具有不同功率级别的模型，适用于不同的任务，并且能够微调您自己的自定义模型。这些模型可用于从内容生成到语义搜索和分类的所有领域。  
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"github.com/gin-gonic/gin"
)

type FineTuningAPI struct {
}

// Post /v1/fine_tuning/jobs/:fine_tuning_job_id/cancel
// 取消微调 
func (api *FineTuningAPI) V1FineTuningJobsFineTuningJobIdCancelPost(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Get /v1/fine_tuning/jobs/:fine_tuning_job_id/events
// 列出微调事件 
func (api *FineTuningAPI) V1FineTuningJobsFineTuningJobIdEventsGet(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Get /v1/fine_tuning/jobs/:fine_tuning_job_id
// 检索微调作业 
func (api *FineTuningAPI) V1FineTuningJobsFineTuningJobIdGet(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Get /v1/fine_tuning/jobs
// 列出微调作业 
func (api *FineTuningAPI) V1FineTuningJobsGet(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Post /v1/fine_tuning/jobs
// 创建微调作业 
func (api *FineTuningAPI) V1FineTuningJobsPost(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

