/*
 * OpenAI（ChatGPT）
 *
 * Open AI（ChatGPT）几乎可以应用于任何涉及理解或生成自然语言或代码的任务。我们提供一系列具有不同功率级别的模型，适用于不同的任务，并且能够微调您自己的自定义模型。这些模型可用于从内容生成到语义搜索和分类的所有领域。  
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"github.com/gin-gonic/gin"
)

type AudioAPI interface {


    // V1AudioSpeechGet Get /v1/audio/speech
    // 创建语音 
     V1AudioSpeechGet(c *gin.Context)

    // V1AudioTranscriptionsGet Get /v1/audio/transcriptions
    // 创建转录 
     V1AudioTranscriptionsGet(c *gin.Context)

    // V1AudioTranscriptionsPost Post /v1/audio/transcriptions
    // 创建转录 
     V1AudioTranscriptionsPost(c *gin.Context)

    // V1AudioTranslationsGet Get /v1/audio/translations
    // 创建翻译 
     V1AudioTranslationsGet(c *gin.Context)

    // V1AudioTranslationsPost Post /v1/audio/translations
    // 创建翻译 
     V1AudioTranslationsPost(c *gin.Context)

}