/*
 * OpenAI（ChatGPT）
 *
 * Open AI（ChatGPT）几乎可以应用于任何涉及理解或生成自然语言或代码的任务。我们提供一系列具有不同功率级别的模型，适用于不同的任务，并且能够微调您自己的自定义模型。这些模型可用于从内容生成到语义搜索和分类的所有领域。  
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type V1AudioSpeechGetRequest struct {

	// 可用的 TTS 模型之一:tts-1 或 tts-1-hd
	Model string `json:"model"`

	// 要生成音频的文本。最大长度为4096个字符。
	Input string `json:"input"`

	// 生成音频时使用的语音。支持的语音有:alloy、echo、fable、onyx、nova 和 shimmer。
	Voice string `json:"voice"`

	// 默认为 mp3 音频的格式。支持的格式有:mp3、opus、aac 和 flac。
	ResponseFormat string `json:"response_format,omitempty"`

	// 默认为 1 生成的音频速度。选择0.25到4.0之间的值。1.0是默认值。
	Speed float32 `json:"speed,omitempty"`
}
