/*
 * OpenAI（ChatGPT）
 *
 * Open AI（ChatGPT）几乎可以应用于任何涉及理解或生成自然语言或代码的任务。我们提供一系列具有不同功率级别的模型，适用于不同的任务，并且能够微调您自己的自定义模型。这些模型可用于从内容生成到语义搜索和分类的所有领域。  
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type V1ThreadsThreadIdRunsPostRequest struct {

	// 用于执行此运行的助手的 ID 。
	AssistantId string `json:"assistant_id"`

	// 用于执行此运行的模型的 ID 。如果此处提供了值，它将覆盖与助手关联的模型。如果没有，将使用与助手关联的模型。
	Model string `json:"model"`

	// 覆盖助手的默认系统消息。这对于修改每次运行的行为非常有用。
	Instructions string `json:"instructions"`

	// 覆盖助手可用于此运行的工具。这对于修改每次运行的行为非常有用。
	Tools []V1ThreadsThreadIdRunsPostRequestToolsInner `json:"tools,omitempty"`

	// 一组可附加到对象的 16 个键值对。这对于以结构化格式存储有关对象的附加信息非常有用。键的最大长度为 64 个字符，值的最大长度为 512 个字符。
	Metadata map[string]interface{} `json:"metadata,omitempty"`
}
