/*
 * OpenAI（ChatGPT）
 *
 * Open AI（ChatGPT）几乎可以应用于任何涉及理解或生成自然语言或代码的任务。我们提供一系列具有不同功率级别的模型，适用于不同的任务，并且能够微调您自己的自定义模型。这些模型可用于从内容生成到语义搜索和分类的所有领域。  
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// V1FineTuningJobsFineTuningJobIdCancelPost200ResponseHyperparameters - 微调作业使用的超参数。更多详细信息请参阅微调指南
type V1FineTuningJobsFineTuningJobIdCancelPost200ResponseHyperparameters struct {

	NEpochs string `json:"n_epochs"`
}
