/*
 * OpenAI（ChatGPT）
 *
 * Open AI（ChatGPT）几乎可以应用于任何涉及理解或生成自然语言或代码的任务。我们提供一系列具有不同功率级别的模型，适用于不同的任务，并且能够微调您自己的自定义模型。这些模型可用于从内容生成到语义搜索和分类的所有领域。  
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type V1FineTuningJobsPostRequest struct {

	// 包含训练数据的上传文件的 ID。  有关如何上传文件的信息，请参阅[上传文件。](https://platform.openai.com/docs/api-reference/files/upload)  您的数据集必须格式化为 JSONL 文件。此外，您必须上传带有目的的文件`fine-tune`。  有关更多详细信息，请参阅[微调指南。](https://platform.openai.com/docs/guides/fine-tuning)
	TrainingFile string `json:"training_file"`

	// 要微调的模型的名称。您可以选择支持的模型之一。
	Model string `json:"model"`

	Hyperparameters V1FineTuningJobsPostRequestHyperparameters `json:"hyperparameters,omitempty"`

	// 最多 18 个字符的字符串，将添加到您的微调模型名称中。  例如，`suffix`“custom-model-name”的 a 将生成类似 的模型名称`ft:gpt-3.5-turbo:openai:custom-model-name:7p4lURel`。
	Suffix string `json:"suffix"`

	// 如果您提供此文件，则数据将用于在微调期间定期生成验证指标。这些指标可以在微调结果文件中查看。相同的数据不应同时出现在训练文件和验证文件中。  您的数据集必须格式化为 JSONL 文件。您必须以特定目的上传文件`fine-tune`。  有关更多详细信息，请参阅[微调指南。](https://platform.openai.com/docs/guides/fine-tuning)
	ValidationFile string `json:"validation_file"`
}
