/*
 * OpenAI（ChatGPT）
 *
 * Open AI（ChatGPT）几乎可以应用于任何涉及理解或生成自然语言或代码的任务。我们提供一系列具有不同功率级别的模型，适用于不同的任务，并且能够微调您自己的自定义模型。这些模型可用于从内容生成到语义搜索和分类的所有领域。  
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type V1ModerationsPost200Response struct {

	// 审核任务的唯一标识符
	Id string `json:"id"`

	// 用于审核的模型
	Model string `json:"model"`

	// 审核结果的详细信息
	Results []V1ModerationsPost200ResponseResultsInner `json:"results"`
}
