/*
 * OpenAI（ChatGPT）
 *
 * Open AI（ChatGPT）几乎可以应用于任何涉及理解或生成自然语言或代码的任务。我们提供一系列具有不同功率级别的模型，适用于不同的任务，并且能够微调您自己的自定义模型。这些模型可用于从内容生成到语义搜索和分类的所有领域。  
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// V1FineTuningJobsPostRequestHyperparameters - 用于微调工作的超参数。
type V1FineTuningJobsPostRequestHyperparameters struct {

	// 每批中的示例数。批量大小越大意味着模型参数的更新频率越低，但方差越小。
	BatchSize string `json:"batch_size,omitempty"`

	// 学习率的比例因子。较小的学习率可能有助于避免过度拟合。
	LearningRateMultiplier string `json:"learning_rate_multiplier,omitempty"`

	// 训练模型的纪元数。一个纪元是指训练数据集的一个完整周期。
	NEpochs string `json:"n_epochs,omitempty"`
}
